/* GENERATED by scripts/ui-texts.mts – do not edit by hand. Run `npm run ui-texts`. */
import type { UiText } from "./ui-texts";

export const uiTextCatalog: UiText[] = [
  {
    "id": "dict.meta.title",
    "group": "Назва сайту для пошуку й соцмереж",
    "text": {
      "uk": "НаСвітло – рішення міжнародних судів щодо війни проти України",
      "en": "NaSvitlo – international court decisions on the war against Ukraine"
    },
    "base": {
      "uk": "НаСвітло – рішення міжнародних судів щодо війни проти України",
      "en": "NaSvitlo – international court decisions on the war against Ukraine"
    }
  },
  {
    "id": "dict.meta.description",
    "group": "Назва сайту для пошуку й соцмереж",
    "text": {
      "uk": "Відкрита бібліотека рішень міжнародних судів щодо війни Росії проти України: ЄСПЛ, Міжнародний суд ООН, ICC, арбітражі. Проєкт Факультету права УКУ.",
      "en": "An open library of international court decisions on Russia's war against Ukraine: the ECtHR, ICJ, ICC and arbitral tribunals. UCU Faculty of Law."
    },
    "base": {
      "uk": "Відкрита бібліотека рішень міжнародних судів щодо війни Росії проти України: ЄСПЛ, Міжнародний суд ООН, ICC, арбітражі. Проєкт Факультету права УКУ.",
      "en": "An open library of international court decisions on Russia's war against Ukraine: the ECtHR, ICJ, ICC and arbitral tribunals. UCU Faculty of Law."
    }
  },
  {
    "id": "dict.meta.ogAlt",
    "group": "Назва сайту для пошуку й соцмереж",
    "text": {
      "uk": "НаСвітло – бібліотека рішень міжнародних судів",
      "en": "NaSvitlo – library of international court decisions"
    },
    "base": {
      "uk": "НаСвітло – бібліотека рішень міжнародних судів",
      "en": "NaSvitlo – library of international court decisions"
    }
  },
  {
    "id": "dict.nav.skip",
    "group": "Меню й шапка",
    "text": {
      "uk": "Перейти до змісту",
      "en": "Skip to content"
    },
    "base": {
      "uk": "Перейти до змісту",
      "en": "Skip to content"
    }
  },
  {
    "id": "dict.nav.menu",
    "group": "Меню й шапка",
    "text": {
      "uk": "Меню",
      "en": "Menu"
    },
    "base": {
      "uk": "Меню",
      "en": "Menu"
    }
  },
  {
    "id": "dict.nav.home",
    "group": "Меню й шапка",
    "text": {
      "uk": "Головна",
      "en": "Home"
    },
    "base": {
      "uk": "Головна",
      "en": "Home"
    }
  },
  {
    "id": "dict.nav.about",
    "group": "Меню й шапка",
    "text": {
      "uk": "Про проєкт",
      "en": "About the project"
    },
    "base": {
      "uk": "Про проєкт",
      "en": "About the project"
    }
  },
  {
    "id": "dict.nav.decisions",
    "group": "Меню й шапка",
    "text": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    },
    "base": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    }
  },
  {
    "id": "dict.nav.map",
    "group": "Меню й шапка",
    "text": {
      "uk": "Мапа",
      "en": "Map"
    },
    "base": {
      "uk": "Мапа",
      "en": "Map"
    }
  },
  {
    "id": "dict.nav.team",
    "group": "Меню й шапка",
    "text": {
      "uk": "Команда",
      "en": "Team"
    },
    "base": {
      "uk": "Команда",
      "en": "Team"
    }
  },
  {
    "id": "dict.nav.blog",
    "group": "Меню й шапка",
    "text": {
      "uk": "Блог",
      "en": "Blog"
    },
    "base": {
      "uk": "Блог",
      "en": "Blog"
    }
  },
  {
    "id": "dict.brand.facultyAlt",
    "group": "Назва й логотип",
    "text": {
      "uk": "Факультет права УКУ",
      "en": "UCU Faculty of Law"
    },
    "base": {
      "uk": "Факультет права УКУ",
      "en": "UCU Faculty of Law"
    }
  },
  {
    "id": "dict.brand.wordmark",
    "group": "Назва й логотип",
    "text": {
      "uk": "НаСвітло",
      "en": "NaSvitlo"
    },
    "base": {
      "uk": "НаСвітло",
      "en": "NaSvitlo"
    }
  },
  {
    "id": "dict.hero.credit",
    "group": "Головна: шапка",
    "text": {
      "uk": "Проєкт",
      "en": "A project of"
    },
    "base": {
      "uk": "Проєкт",
      "en": "A project of"
    }
  },
  {
    "id": "dict.hero.creditCentre",
    "group": "Головна: шапка",
    "text": {
      "uk": "Дослідницького центру Луї Зона",
      "en": "the Louis Sohn Research Centre"
    },
    "base": {
      "uk": "Дослідницького центру Луї Зона",
      "en": "the Louis Sohn Research Centre"
    }
  },
  {
    "id": "dict.hero.creditFaculty",
    "group": "Головна: шапка",
    "text": {
      "uk": "Факультету права УКУ",
      "en": "UCU Faculty of Law"
    },
    "base": {
      "uk": "Факультету права УКУ",
      "en": "UCU Faculty of Law"
    }
  },
  {
    "id": "dict.hero.lead",
    "group": "Головна: шапка",
    "text": {
      "uk": "Бібліотека відповідальності та правосуддя для України – освітлюємо правовий шлях, яким Україна крокує до справедливості",
      "en": "The Library of Accountability and Justice for Ukraine – lighting the legal road Ukraine is walking towards justice"
    },
    "base": {
      "uk": "Бібліотека відповідальності та правосуддя для України – освітлюємо правовий шлях, яким Україна крокує до справедливості",
      "en": "The Library of Accountability and Justice for Ukraine – lighting the legal road Ukraine is walking towards justice"
    }
  },
  {
    "id": "dict.hero.ctaRegistry",
    "group": "Головна: шапка",
    "text": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    },
    "base": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    }
  },
  {
    "id": "dict.hero.chainHint",
    "group": "Головна: шапка",
    "text": {
      "uk": "потягніть за ланцюжок",
      "en": "pull the cord"
    },
    "base": {
      "uk": "потягніть за ланцюжок",
      "en": "pull the cord"
    }
  },
  {
    "id": "dict.hero.lampLabel",
    "group": "Головна: шапка",
    "text": {
      "uk": "Увімкнути або вимкнути лампу",
      "en": "Turn the lamp on or off"
    },
    "base": {
      "uk": "Увімкнути або вимкнути лампу",
      "en": "Turn the lamp on or off"
    }
  },
  {
    "id": "dict.intro.text",
    "group": "Головна: вступ",
    "text": {
      "uk": "Онлайн-бібліотека міжнародної судової практики (Міжнародний суд ООН, ЄСПЛ, МКС, Міжнародний трибунал з морського права, Постійна палата третейського суду) та практики іноземних судів у справах щодо притягнення Росії до відповідальності за порушення, вчинені під час війни проти України.",
      "en": "An online library of international case-law (the International Court of Justice, the ECtHR, the ICC, the International Tribunal for the Law of the Sea, the Permanent Court of Arbitration) and of foreign national courts, in proceedings to hold Russia accountable for violations committed during the war against Ukraine."
    },
    "base": {
      "uk": "Онлайн-бібліотека міжнародної судової практики (Міжнародний суд ООН, ЄСПЛ, МКС, Міжнародний трибунал з морського права, Постійна палата третейського суду) та практики іноземних судів у справах щодо притягнення Росії до відповідальності за порушення, вчинені під час війни проти України.",
      "en": "An online library of international case-law (the International Court of Justice, the ECtHR, the ICC, the International Tribunal for the Law of the Sea, the Permanent Court of Arbitration) and of foreign national courts, in proceedings to hold Russia accountable for violations committed during the war against Ukraine."
    }
  },
  {
    "id": "dict.intro.about",
    "group": "Головна: вступ",
    "text": {
      "uk": "Про нас",
      "en": "About us"
    },
    "base": {
      "uk": "Про нас",
      "en": "About us"
    }
  },
  {
    "id": "dict.about.more",
    "group": "Головна: «Про проєкт»",
    "text": {
      "uk": "Докладніше про проєкт",
      "en": "More about the project"
    },
    "base": {
      "uk": "Докладніше про проєкт",
      "en": "More about the project"
    }
  },
  {
    "id": "dict.pending.title",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Ще досліджуємо",
      "en": "Still being researched"
    },
    "base": {
      "uk": "Ще досліджуємо",
      "en": "Still being researched"
    }
  },
  {
    "id": "dict.pending.body",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Цю справу вже внесено до бібліотеки, але огляду ще немає – ми над ним працюємо. Нижче те, що вже відомо, і посилання на документ суду, якщо він у відкритому доступі.",
      "en": "This proceeding is in the library, but its summary is not written yet – we are working on it. Below is what is already known, and a link to the court's own document where one is public."
    },
    "base": {
      "uk": "Цю справу вже внесено до бібліотеки, але огляду ще немає – ми над ним працюємо. Нижче те, що вже відомо, і посилання на документ суду, якщо він у відкритому доступі.",
      "en": "This proceeding is in the library, but its summary is not written yet – we are working on it. Below is what is already known, and a link to the court's own document where one is public."
    }
  },
  {
    "id": "dict.pending.forum",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Суд",
      "en": "Court"
    },
    "base": {
      "uk": "Суд",
      "en": "Court"
    }
  },
  {
    "id": "dict.pending.status",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Стан",
      "en": "Stage"
    },
    "base": {
      "uk": "Стан",
      "en": "Stage"
    }
  },
  {
    "id": "dict.pending.kind",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Галузь",
      "en": "Field"
    },
    "base": {
      "uk": "Галузь",
      "en": "Field"
    }
  },
  {
    "id": "dict.pending.docket",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Реєстраційний номер",
      "en": "Docket"
    },
    "base": {
      "uk": "Реєстраційний номер",
      "en": "Docket"
    }
  },
  {
    "id": "dict.pending.official",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "Документ суду",
      "en": "The court's document"
    },
    "base": {
      "uk": "Документ суду",
      "en": "The court's document"
    }
  },
  {
    "id": "dict.pending.toRegistry",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "До бібліотеки рішень",
      "en": "The library of decisions"
    },
    "base": {
      "uk": "До бібліотеки рішень",
      "en": "The library of decisions"
    }
  },
  {
    "id": "dict.pending.toMap",
    "group": "Сторінка «Ще досліджуємо» (загальне)",
    "text": {
      "uk": "До мапи",
      "en": "The map"
    },
    "base": {
      "uk": "До мапи",
      "en": "The map"
    }
  },
  {
    "id": "dict.quote.text",
    "group": "Головна: цитата",
    "text": {
      "uk": "Російська Федерація повинна негайно призупинити воєнні операції, які вона розпочала 24 лютого 2022 року на території України",
      "en": "The Russian Federation shall immediately suspend the military operations that it commenced on 24 February 2022 in the territory of Ukraine"
    },
    "base": {
      "uk": "Російська Федерація повинна негайно призупинити воєнні операції, які вона розпочала 24 лютого 2022 року на території України",
      "en": "The Russian Federation shall immediately suspend the military operations that it commenced on 24 February 2022 in the territory of Ukraine"
    }
  },
  {
    "id": "dict.quote.source",
    "group": "Головна: цитата",
    "text": {
      "uk": "Міжнародний суд ООН · Тимчасові заходи · 16 березня 2022",
      "en": "International Court of Justice · Provisional Measures · 16 March 2022"
    },
    "base": {
      "uk": "Міжнародний суд ООН · Тимчасові заходи · 16 березня 2022",
      "en": "International Court of Justice · Provisional Measures · 16 March 2022"
    }
  },
  {
    "id": "dict.quote.read",
    "group": "Головна: цитата",
    "text": {
      "uk": "Читати рішення",
      "en": "Read the decision"
    },
    "base": {
      "uk": "Читати рішення",
      "en": "Read the decision"
    }
  },
  {
    "id": "dict.mapSection.close",
    "group": "Мапа",
    "text": {
      "uk": "Закрити картку",
      "en": "Close card"
    },
    "base": {
      "uk": "Закрити картку",
      "en": "Close card"
    }
  },
  {
    "id": "dict.mapSection.moveCard",
    "group": "Мапа",
    "text": {
      "uk": "Перетягнути картку",
      "en": "Move the card"
    },
    "base": {
      "uk": "Перетягнути картку",
      "en": "Move the card"
    }
  },
  {
    "id": "dict.mapSection.label",
    "group": "Мапа",
    "text": {
      "uk": "Мапа",
      "en": "Map"
    },
    "base": {
      "uk": "Мапа",
      "en": "Map"
    }
  },
  {
    "id": "dict.mapSection.heading",
    "group": "Мапа",
    "text": {
      "uk": "Держави, чиї суди розглядають ці справи",
      "en": "The states whose courts hear these cases"
    },
    "base": {
      "uk": "Держави, чиї суди розглядають ці справи",
      "en": "The states whose courts hear these cases"
    }
  },
  {
    "id": "dict.mapSection.legendCourt",
    "group": "Мапа",
    "text": {
      "uk": "Суд",
      "en": "Court"
    },
    "base": {
      "uk": "Суд",
      "en": "Court"
    }
  },
  {
    "id": "dict.mapSection.legendLit",
    "group": "Мапа",
    "text": {
      "uk": "Є огляд",
      "en": "Written up"
    },
    "base": {
      "uk": "Є огляд",
      "en": "Written up"
    }
  },
  {
    "id": "dict.mapSection.legendUnlit",
    "group": "Мапа",
    "text": {
      "uk": "Ще досліджуємо",
      "en": "Still researching"
    },
    "base": {
      "uk": "Ще досліджуємо",
      "en": "Still researching"
    }
  },
  {
    "id": "dict.mapSection.courtsSeat",
    "group": "Мапа",
    "text": {
      "uk": "Суди засідають у",
      "en": "The courts sit in"
    },
    "base": {
      "uk": "Суди засідають у",
      "en": "The courts sit in"
    }
  },
  {
    "id": "dict.mapSection.courtHears",
    "group": "Мапа",
    "text": {
      "uk": "Розглядає справи",
      "en": "Hears"
    },
    "base": {
      "uk": "Розглядає справи",
      "en": "Hears"
    }
  },
  {
    "id": "dict.mapSection.inLibrary",
    "group": "Мапа",
    "text": {
      "uk": "Які саме",
      "en": "Which ones"
    },
    "base": {
      "uk": "Які саме",
      "en": "Which ones"
    }
  },
  {
    "id": "dict.mapSection.caseload",
    "group": "Мапа",
    "text": {
      "uk": "{n} {w} у бібліотеці",
      "en": "{n} {w} in the library"
    },
    "base": {
      "uk": "{n} {w} у бібліотеці",
      "en": "{n} {w} in the library"
    }
  },
  {
    "id": "dict.mapSection.seatsTotal",
    "group": "Мапа",
    "text": {
      "uk": "Усього {at}: {n} {w}",
      "en": "Total {at}: {n} {w}"
    },
    "base": {
      "uk": "Усього {at}: {n} {w}",
      "en": "Total {at}: {n} {w}"
    }
  },
  {
    "id": "dict.mapSection.seatsNational",
    "group": "Мапа",
    "text": {
      "uk": "Національні суди",
      "en": "National courts"
    },
    "base": {
      "uk": "Національні суди",
      "en": "National courts"
    }
  },
  {
    "id": "dict.mapSection.seatsOpen",
    "group": "Мапа",
    "text": {
      "uk": "Показати в бібліотеці",
      "en": "Show in the library"
    },
    "base": {
      "uk": "Показати в бібліотеці",
      "en": "Show in the library"
    }
  },
  {
    "id": "dict.mapSection.caseloadWord.one",
    "group": "Мапа",
    "text": {
      "uk": "провадження",
      "en": "proceeding"
    },
    "base": {
      "uk": "провадження",
      "en": "proceeding"
    }
  },
  {
    "id": "dict.mapSection.caseloadWord.few",
    "group": "Мапа",
    "text": {
      "uk": "провадження",
      "en": "proceedings"
    },
    "base": {
      "uk": "провадження",
      "en": "proceedings"
    }
  },
  {
    "id": "dict.mapSection.caseloadWord.many",
    "group": "Мапа",
    "text": {
      "uk": "проваджень",
      "en": "proceedings"
    },
    "base": {
      "uk": "проваджень",
      "en": "proceedings"
    }
  },
  {
    "id": "dict.mapSection.zoomLabel",
    "group": "Мапа",
    "text": {
      "uk": "Масштаб",
      "en": "Framing"
    },
    "base": {
      "uk": "Масштаб",
      "en": "Framing"
    }
  },
  {
    "id": "dict.mapSection.zoomWide",
    "group": "Мапа",
    "text": {
      "uk": "Європа",
      "en": "Europe"
    },
    "base": {
      "uk": "Європа",
      "en": "Europe"
    }
  },
  {
    "id": "dict.mapSection.zoomClose",
    "group": "Мапа",
    "text": {
      "uk": "Україна",
      "en": "Ukraine"
    },
    "base": {
      "uk": "Україна",
      "en": "Ukraine"
    }
  },
  {
    "id": "dict.mapSection.zoomAtlantic",
    "group": "Мапа",
    "text": {
      "uk": "Вся мапа",
      "en": "Everything"
    },
    "base": {
      "uk": "Вся мапа",
      "en": "Everything"
    }
  },
  {
    "id": "dict.mapSection.zoomReset",
    "group": "Мапа",
    "text": {
      "uk": "Відцентрувати",
      "en": "Recentre"
    },
    "base": {
      "uk": "Відцентрувати",
      "en": "Recentre"
    }
  },
  {
    "id": "dict.mapSection.zoomIn",
    "group": "Мапа",
    "text": {
      "uk": "Наблизити",
      "en": "Zoom in"
    },
    "base": {
      "uk": "Наблизити",
      "en": "Zoom in"
    }
  },
  {
    "id": "dict.mapSection.zoomOut",
    "group": "Мапа",
    "text": {
      "uk": "Віддалити",
      "en": "Zoom out"
    },
    "base": {
      "uk": "Віддалити",
      "en": "Zoom out"
    }
  },
  {
    "id": "dict.mapSection.wheelHint",
    "group": "Мапа",
    "text": {
      "uk": "Ctrl або ⌘ + прокручування – масштаб",
      "en": "Ctrl or ⌘ + scroll to zoom"
    },
    "base": {
      "uk": "Ctrl або ⌘ + прокручування – масштаб",
      "en": "Ctrl or ⌘ + scroll to zoom"
    }
  },
  {
    "id": "dict.mapSection.overview",
    "group": "Мапа",
    "text": {
      "uk": "Оглядова мапа. Натисніть на суд у списку нижче – або відкрийте на весь екран.",
      "en": "An overview map. Pick a court from the list below, or open it full screen."
    },
    "base": {
      "uk": "Оглядова мапа. Натисніть на суд у списку нижче – або відкрийте на весь екран.",
      "en": "An overview map. Pick a court from the list below, or open it full screen."
    }
  },
  {
    "id": "dict.mapSection.openFull",
    "group": "Мапа",
    "text": {
      "uk": "На весь екран",
      "en": "Full screen"
    },
    "base": {
      "uk": "На весь екран",
      "en": "Full screen"
    }
  },
  {
    "id": "dict.mapSection.closeFull",
    "group": "Мапа",
    "text": {
      "uk": "Вийти з повного екрана",
      "en": "Leave full screen"
    },
    "base": {
      "uk": "Вийти з повного екрана",
      "en": "Leave full screen"
    }
  },
  {
    "id": "dict.mapSection.reads",
    "group": "Мапа",
    "text": {
      "uk": "Опрацьовані рішення",
      "en": "Decisions written up"
    },
    "base": {
      "uk": "Опрацьовані рішення",
      "en": "Decisions written up"
    }
  },
  {
    "id": "dict.mapSection.writtenOf",
    "group": "Мапа",
    "text": {
      "uk": "Опрацьовано {n} з {total}",
      "en": "Written up: {n} of {total}"
    },
    "base": {
      "uk": "Опрацьовано {n} з {total}",
      "en": "Written up: {n} of {total}"
    }
  },
  {
    "id": "dict.mapSection.writtenBehind",
    "group": "Мапа",
    "text": {
      "uk": "Розібрано ситуацію, з якої видано ці ордери",
      "en": "The situation these warrants issue from is written up"
    },
    "base": {
      "uk": "Розібрано ситуацію, з якої видано ці ордери",
      "en": "The situation these warrants issue from is written up"
    }
  },
  {
    "id": "dict.mapSection.allInRegistry",
    "group": "Мапа",
    "text": {
      "uk": "Дивитися в бібліотеці",
      "en": "See them in the library"
    },
    "base": {
      "uk": "Дивитися в бібліотеці",
      "en": "See them in the library"
    }
  },
  {
    "id": "dict.mapSection.pending",
    "group": "Мапа",
    "text": {
      "uk": "Огляд у підготовці",
      "en": "Summary in preparation"
    },
    "base": {
      "uk": "Огляд у підготовці",
      "en": "Summary in preparation"
    }
  },
  {
    "id": "dict.mapSection.amountLabel",
    "group": "Мапа",
    "text": {
      "uk": "Сума у спорі",
      "en": "Amount in dispute"
    },
    "base": {
      "uk": "Сума у спорі",
      "en": "Amount in dispute"
    }
  },
  {
    "id": "dict.mapSection.legendWhat",
    "group": "Мапа",
    "text": {
      "uk": "Місця подій",
      "en": "Places"
    },
    "base": {
      "uk": "Місця подій",
      "en": "Places"
    }
  },
  {
    "id": "dict.mapSection.legendTitle",
    "group": "Мапа",
    "text": {
      "uk": "Легенда",
      "en": "Key"
    },
    "base": {
      "uk": "Легенда",
      "en": "Key"
    }
  },
  {
    "id": "dict.mapSection.placesTitle",
    "group": "Мапа",
    "text": {
      "uk": "Місця подій",
      "en": "The places"
    },
    "base": {
      "uk": "Місця подій",
      "en": "The places"
    }
  },
  {
    "id": "dict.mapSection.legendHow",
    "group": "Мапа",
    "text": {
      "uk": "Що на мапі",
      "en": "What is on the map"
    },
    "base": {
      "uk": "Що на мапі",
      "en": "What is on the map"
    }
  },
  {
    "id": "dict.mapSection.legendLine",
    "group": "Мапа",
    "text": {
      "uk": "Звʼязок суду з подією",
      "en": "A court's link to an event"
    },
    "base": {
      "uk": "Звʼязок суду з подією",
      "en": "A court's link to an event"
    }
  },
  {
    "id": "dict.mapSection.legendForum",
    "group": "Мапа",
    "text": {
      "uk": "Держава, чиї суди розглядають ці справи",
      "en": "A state whose courts hear these cases"
    },
    "base": {
      "uk": "Держава, чиї суди розглядають ці справи",
      "en": "A state whose courts hear these cases"
    }
  },
  {
    "id": "dict.mapSection.legendOffMap",
    "group": "Мапа",
    "text": {
      "uk": "Суд поза кадром",
      "en": "A court outside the frame"
    },
    "base": {
      "uk": "Суд поза кадром",
      "en": "A court outside the frame"
    }
  },
  {
    "id": "dict.mapSection.legendRegions",
    "group": "Мапа",
    "text": {
      "uk": "Межі областей",
      "en": "Oblast boundaries"
    },
    "base": {
      "uk": "Межі областей",
      "en": "Oblast boundaries"
    }
  },
  {
    "id": "dict.mapSection.legendArea",
    "group": "Мапа",
    "text": {
      "uk": "Подія – про всю підсвічену територію",
      "en": "About all the lit ground"
    },
    "base": {
      "uk": "Подія – про всю підсвічену територію",
      "en": "About all the lit ground"
    }
  },
  {
    "id": "dict.mapSection.legendPick",
    "group": "Мапа",
    "text": {
      "uk": "Натисніть на суд – побачите справи, які він розглядає.",
      "en": "Press a court to see the cases it hears."
    },
    "base": {
      "uk": "Натисніть на суд – побачите справи, які він розглядає.",
      "en": "Press a court to see the cases it hears."
    }
  },
  {
    "id": "dict.mapSection.pageTitle",
    "group": "Мапа",
    "text": {
      "uk": "Мапа судів",
      "en": "The map of courts"
    },
    "base": {
      "uk": "Мапа судів",
      "en": "The map of courts"
    }
  },
  {
    "id": "dict.mapSection.pageLede",
    "group": "Мапа",
    "text": {
      "uk": "Порушення сталися в Україні, а судять їх за тисячі кілометрів звідти. Мапа показує, куди саме сягнула відповідь: держави, чиї суди ведуть ці провадження.",
      "en": "The violations happened in Ukraine; they are judged thousands of kilometres away. The map shows how far the answer reached: the states whose courts are hearing these proceedings."
    },
    "base": {
      "uk": "Порушення сталися в Україні, а судять їх за тисячі кілометрів звідти. Мапа показує, куди саме сягнула відповідь: держави, чиї суди ведуть ці провадження.",
      "en": "The violations happened in Ukraine; they are judged thousands of kilometres away. The map shows how far the answer reached: the states whose courts are hearing these proceedings."
    }
  },
  {
    "id": "dict.mapSection.backHome",
    "group": "Мапа",
    "text": {
      "uk": "На головну",
      "en": "Home"
    },
    "base": {
      "uk": "На головну",
      "en": "Home"
    }
  },
  {
    "id": "dict.registry.stageName",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Стан розгляду",
      "en": "Stage"
    },
    "base": {
      "uk": "Стан розгляду",
      "en": "Stage"
    }
  },
  {
    "id": "dict.registry.outcomeName",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Тип",
      "en": "Decision type"
    },
    "base": {
      "uk": "Тип",
      "en": "Decision type"
    }
  },
  {
    "id": "dict.registry.stage.preliminary",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Попередній етап",
      "en": "Preliminary stage"
    },
    "base": {
      "uk": "Попередній етап",
      "en": "Preliminary stage"
    }
  },
  {
    "id": "dict.registry.stage.investigation",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Розслідування",
      "en": "Investigation"
    },
    "base": {
      "uk": "Розслідування",
      "en": "Investigation"
    }
  },
  {
    "id": "dict.registry.stage.merits",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Розгляд по суті",
      "en": "Merits pending"
    },
    "base": {
      "uk": "Розгляд по суті",
      "en": "Merits pending"
    }
  },
  {
    "id": "dict.registry.stage.satisfaction",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Очікує сатисфакції",
      "en": "Awaiting satisfaction"
    },
    "base": {
      "uk": "Очікує сатисфакції",
      "en": "Awaiting satisfaction"
    }
  },
  {
    "id": "dict.registry.stage.appeal",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Оскаржується",
      "en": "Under appeal"
    },
    "base": {
      "uk": "Оскаржується",
      "en": "Under appeal"
    }
  },
  {
    "id": "dict.registry.stage.remitted",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Новий розгляд",
      "en": "Remitted"
    },
    "base": {
      "uk": "Новий розгляд",
      "en": "Remitted"
    }
  },
  {
    "id": "dict.registry.stage.enforcement",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Виконання",
      "en": "Enforcement"
    },
    "base": {
      "uk": "Виконання",
      "en": "Enforcement"
    }
  },
  {
    "id": "dict.registry.stage.suspended",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Призупинено",
      "en": "Suspended"
    },
    "base": {
      "uk": "Призупинено",
      "en": "Suspended"
    }
  },
  {
    "id": "dict.registry.stage.frozen",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Заморожено",
      "en": "Frozen"
    },
    "base": {
      "uk": "Заморожено",
      "en": "Frozen"
    }
  },
  {
    "id": "dict.registry.stage.upcoming",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "До розгляду",
      "en": "Yet to be heard"
    },
    "base": {
      "uk": "До розгляду",
      "en": "Yet to be heard"
    }
  },
  {
    "id": "dict.registry.stage.concluded",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Завершено",
      "en": "Concluded"
    },
    "base": {
      "uk": "Завершено",
      "en": "Concluded"
    }
  },
  {
    "id": "dict.registry.outcome.judgment",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Рішення",
      "en": "Judgment"
    },
    "base": {
      "uk": "Рішення",
      "en": "Judgment"
    }
  },
  {
    "id": "dict.registry.outcome.award",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Остаточне рішення",
      "en": "Final award"
    },
    "base": {
      "uk": "Остаточне рішення",
      "en": "Final award"
    }
  },
  {
    "id": "dict.registry.outcome.verdict",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Вирок",
      "en": "Verdict"
    },
    "base": {
      "uk": "Вирок",
      "en": "Verdict"
    }
  },
  {
    "id": "dict.registry.outcome.liability",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Відповідальність",
      "en": "Liability established"
    },
    "base": {
      "uk": "Відповідальність",
      "en": "Liability established"
    }
  },
  {
    "id": "dict.registry.outcome.warrant",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Ордер",
      "en": "Warrant"
    },
    "base": {
      "uk": "Ордер",
      "en": "Warrant"
    }
  },
  {
    "id": "dict.registry.outcome.upheld",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Арбітраж залишено",
      "en": "Arbitration upheld"
    },
    "base": {
      "uk": "Арбітраж залишено",
      "en": "Arbitration upheld"
    }
  },
  {
    "id": "dict.registry.outcome.procedural",
    "group": "Бібліотека рішень: стадії й типи",
    "text": {
      "uk": "Процедурне",
      "en": "Procedural"
    },
    "base": {
      "uk": "Процедурне",
      "en": "Procedural"
    }
  },
  {
    "id": "dict.newsletter.heading",
    "group": "Розсилка",
    "text": {
      "uk": "Щомісяця – ще кілька рішень НаСвітло",
      "en": "Each month, a few more decisions brought to light"
    },
    "base": {
      "uk": "Щомісяця – ще кілька рішень НаСвітло",
      "en": "Each month, a few more decisions brought to light"
    }
  },
  {
    "id": "dict.newsletter.text",
    "group": "Розсилка",
    "text": {
      "uk": "Лист про те, які рішення ми опрацювали за місяць: що встановив суд і на що з цього можна опертися.",
      "en": "A letter on the decisions we summarised over the month: what the court found, and what of it can be relied on."
    },
    "base": {
      "uk": "Лист про те, які рішення ми опрацювали за місяць: що встановив суд і на що з цього можна опертися.",
      "en": "A letter on the decisions we summarised over the month: what the court found, and what of it can be relied on."
    }
  },
  {
    "id": "dict.newsletter.subscribe",
    "group": "Розсилка",
    "text": {
      "uk": "Отримувати листа",
      "en": "Get the letter"
    },
    "base": {
      "uk": "Отримувати листа",
      "en": "Get the letter"
    }
  },
  {
    "id": "dict.newsletter.support",
    "group": "Розсилка",
    "text": {
      "uk": "Підтримати бібліотеку",
      "en": "Support the library"
    },
    "base": {
      "uk": "Підтримати бібліотеку",
      "en": "Support the library"
    }
  },
  {
    "id": "dict.newsletter.assurance",
    "group": "Розсилка",
    "text": {
      "uk": "Тільки огляди. Відписатися можна з будь-якого листа.",
      "en": "Summaries only. Unsubscribe from any letter."
    },
    "base": {
      "uk": "Тільки огляди. Відписатися можна з будь-якого листа.",
      "en": "Summaries only. Unsubscribe from any letter."
    }
  },
  {
    "id": "dict.partners.label",
    "group": "Головна: партнери",
    "text": {
      "uk": "Партнери",
      "en": "Partners"
    },
    "base": {
      "uk": "Партнери",
      "en": "Partners"
    }
  },
  {
    "id": "dict.partners.heading",
    "group": "Головна: партнери",
    "text": {
      "uk": "З ким ми працюємо",
      "en": "Who we work with"
    },
    "base": {
      "uk": "З ким ми працюємо",
      "en": "Who we work with"
    }
  },
  {
    "id": "dict.partners.funded",
    "group": "Головна: партнери",
    "text": {
      "uk": "Проєкт створено за підтримки",
      "en": "The project was made with the support of"
    },
    "base": {
      "uk": "Проєкт створено за підтримки",
      "en": "The project was made with the support of"
    }
  },
  {
    "id": "dict.partners.openLabel",
    "group": "Головна: партнери",
    "text": {
      "uk": "Відкриті до партнерства",
      "en": "Open to partnership"
    },
    "base": {
      "uk": "Відкриті до партнерства",
      "en": "Open to partnership"
    }
  },
  {
    "id": "dict.partners.openHeading",
    "group": "Головна: партнери",
    "text": {
      "uk": "Бібліотека росте разом з тими, хто її підтримує",
      "en": "The library grows with those who support it"
    },
    "base": {
      "uk": "Бібліотека росте разом з тими, хто її підтримує",
      "en": "The library grows with those who support it"
    }
  },
  {
    "id": "dict.partners.openText",
    "group": "Головна: партнери",
    "text": {
      "uk": "Ми шукаємо інституції, готові працювати над доступністю міжнародного правосуддя для України.",
      "en": "We are looking for institutions ready to work on the accessibility of international justice for Ukraine."
    },
    "base": {
      "uk": "Ми шукаємо інституції, готові працювати над доступністю міжнародного правосуддя для України.",
      "en": "We are looking for institutions ready to work on the accessibility of international justice for Ukraine."
    }
  },
  {
    "id": "dict.partners.openWays.0",
    "group": "Головна: партнери",
    "text": {
      "uk": "Дослідження",
      "en": "Research"
    },
    "base": {
      "uk": "Дослідження",
      "en": "Research"
    }
  },
  {
    "id": "dict.partners.openWays.1",
    "group": "Головна: партнери",
    "text": {
      "uk": "Освітні події",
      "en": "Educational events"
    },
    "base": {
      "uk": "Освітні події",
      "en": "Educational events"
    }
  },
  {
    "id": "dict.partners.openWays.2",
    "group": "Головна: партнери",
    "text": {
      "uk": "Фінансова підтримка",
      "en": "Financial support"
    },
    "base": {
      "uk": "Фінансова підтримка",
      "en": "Financial support"
    }
  },
  {
    "id": "dict.partners.openCta",
    "group": "Головна: партнери",
    "text": {
      "uk": "Написати нам",
      "en": "Write to us"
    },
    "base": {
      "uk": "Написати нам",
      "en": "Write to us"
    }
  },
  {
    "id": "dict.footer.tagline",
    "group": "Футер",
    "text": {
      "uk": "Бібліотека рішень міжнародних судів щодо війни Росії проти України. Ми проливаємо на них світло.",
      "en": "A library of international court decisions on Russia's war against Ukraine. We shed light on what they say."
    },
    "base": {
      "uk": "Бібліотека рішень міжнародних судів щодо війни Росії проти України. Ми проливаємо на них світло.",
      "en": "A library of international court decisions on Russia's war against Ukraine. We shed light on what they say."
    }
  },
  {
    "id": "dict.footer.org",
    "group": "Футер",
    "text": {
      "uk": "Дослідницький центр Луї Зона",
      "en": "The Louis Sohn Research Centre"
    },
    "base": {
      "uk": "Дослідницький центр Луї Зона",
      "en": "The Louis Sohn Research Centre"
    }
  },
  {
    "id": "dict.footer.faculty",
    "group": "Футер",
    "text": {
      "uk": "Факультет права УКУ",
      "en": "UCU Faculty of Law"
    },
    "base": {
      "uk": "Факультет права УКУ",
      "en": "UCU Faculty of Law"
    }
  },
  {
    "id": "dict.footer.colArchive",
    "group": "Футер",
    "text": {
      "uk": "Бібліотека",
      "en": "Library"
    },
    "base": {
      "uk": "Бібліотека",
      "en": "Library"
    }
  },
  {
    "id": "dict.footer.colCenter",
    "group": "Футер",
    "text": {
      "uk": "Центр",
      "en": "Centre"
    },
    "base": {
      "uk": "Центр",
      "en": "Centre"
    }
  },
  {
    "id": "dict.footer.colContacts",
    "group": "Футер",
    "text": {
      "uk": "Контакти",
      "en": "Contacts"
    },
    "base": {
      "uk": "Контакти",
      "en": "Contacts"
    }
  },
  {
    "id": "dict.footer.linkRegistry",
    "group": "Футер",
    "text": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    },
    "base": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    }
  },
  {
    "id": "dict.footer.linkMap",
    "group": "Футер",
    "text": {
      "uk": "Мапа",
      "en": "Map"
    },
    "base": {
      "uk": "Мапа",
      "en": "Map"
    }
  },
  {
    "id": "dict.footer.linkAbout",
    "group": "Футер",
    "text": {
      "uk": "Про проєкт",
      "en": "About the project"
    },
    "base": {
      "uk": "Про проєкт",
      "en": "About the project"
    }
  },
  {
    "id": "dict.footer.linkTeam",
    "group": "Футер",
    "text": {
      "uk": "Команда",
      "en": "Team"
    },
    "base": {
      "uk": "Команда",
      "en": "Team"
    }
  },
  {
    "id": "dict.footer.linkBlog",
    "group": "Футер",
    "text": {
      "uk": "Блог",
      "en": "Blog"
    },
    "base": {
      "uk": "Блог",
      "en": "Blog"
    }
  },
  {
    "id": "dict.footer.email",
    "group": "Футер",
    "text": {
      "uk": "louis.sohn.center@ucu.edu.ua",
      "en": "louis.sohn.center@ucu.edu.ua"
    },
    "base": {
      "uk": "louis.sohn.center@ucu.edu.ua",
      "en": "louis.sohn.center@ucu.edu.ua"
    }
  },
  {
    "id": "dict.footer.support",
    "group": "Футер",
    "text": {
      "uk": "Підтримати нас",
      "en": "Support us"
    },
    "base": {
      "uk": "Підтримати нас",
      "en": "Support us"
    }
  },
  {
    "id": "dict.footer.address",
    "group": "Футер",
    "text": {
      "uk": "вул. Іларіона Свєнціцького, 17, Львів, 79011",
      "en": "17 Svientsitskoho St., Lviv, 79011"
    },
    "base": {
      "uk": "вул. Іларіона Свєнціцького, 17, Львів, 79011",
      "en": "17 Svientsitskoho St., Lviv, 79011"
    }
  },
  {
    "id": "dict.footer.rights",
    "group": "Футер",
    "text": {
      "uk": "© 2026 Дослідницький центр Луї Зона, УКУ. Матеріали – CC BY 4.0.",
      "en": "© 2026 the Louis Sohn Research Centre, UCU. Materials – CC BY 4.0."
    },
    "base": {
      "uk": "© 2026 Дослідницький центр Луї Зона, УКУ. Матеріали – CC BY 4.0.",
      "en": "© 2026 the Louis Sohn Research Centre, UCU. Materials – CC BY 4.0."
    }
  },
  {
    "id": "dict.footer.privacy",
    "group": "Футер",
    "text": {
      "uk": "Політика конфіденційності",
      "en": "Privacy policy"
    },
    "base": {
      "uk": "Політика конфіденційності",
      "en": "Privacy policy"
    }
  },
  {
    "id": "dict.footer.terms",
    "group": "Футер",
    "text": {
      "uk": "Умови користування",
      "en": "Terms of use"
    },
    "base": {
      "uk": "Умови користування",
      "en": "Terms of use"
    }
  },
  {
    "id": "about.title",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Про проєкт",
      "en": "About the project"
    },
    "base": {
      "uk": "Про проєкт",
      "en": "About the project"
    }
  },
  {
    "id": "about.scope",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Онлайн-бібліотека міжнародної судової практики та практики іноземних судів у справах, які порушили Україна та іноземні держави, щоб притягнути Росію до відповідальності за порушення, вчинені під час війни проти України.",
      "en": "An online library of international case-law and of foreign national courts, in the proceedings brought by Ukraine and by foreign States to hold Russia accountable for violations committed during the war against Ukraine."
    },
    "base": {
      "uk": "Онлайн-бібліотека міжнародної судової практики та практики іноземних судів у справах, які порушили Україна та іноземні держави, щоб притягнути Росію до відповідальності за порушення, вчинені під час війни проти України.",
      "en": "An online library of international case-law and of foreign national courts, in the proceedings brought by Ukraine and by foreign States to hold Russia accountable for violations committed during the war against Ukraine."
    }
  },
  {
    "id": "about.metaDesc",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Хто веде бібліотеку «НаСвітло», що це за проєкт і хто над ним працює.",
      "en": "Who runs the NaSvitlo library, what the project is, and who works on it."
    },
    "base": {
      "uk": "Хто веде бібліотеку «НаСвітло», що це за проєкт і хто над ним працює.",
      "en": "Who runs the NaSvitlo library, what the project is, and who works on it."
    }
  },
  {
    "id": "about.whyH",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Навіщо ця бібліотека",
      "en": "Why this library"
    },
    "base": {
      "uk": "Навіщо ця бібліотека",
      "en": "Why this library"
    }
  },
  {
    "id": "about.resDate",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "27 березня 2014",
      "en": "27 March 2014"
    },
    "base": {
      "uk": "27 березня 2014",
      "en": "27 March 2014"
    }
  },
  {
    "id": "about.resText",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Генеральна Асамблея ООН схвалює резолюцію «Територіальна цілісність України»",
      "en": "The UN General Assembly adopts the resolution ‘Territorial integrity of Ukraine’"
    },
    "base": {
      "uk": "Генеральна Асамблея ООН схвалює резолюцію «Територіальна цілісність України»",
      "en": "The UN General Assembly adopts the resolution ‘Territorial integrity of Ukraine’"
    }
  },
  {
    "id": "about.resLink",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "A/RES/68/262",
      "en": "A/RES/68/262"
    },
    "base": {
      "uk": "A/RES/68/262",
      "en": "A/RES/68/262"
    }
  },
  {
    "id": "about.forumsH",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Інстанції в бібліотеці",
      "en": "The forums in the library"
    },
    "base": {
      "uk": "Інстанції в бібліотеці",
      "en": "The forums in the library"
    }
  },
  {
    "id": "about.forumsNat",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Іноземні національні суди",
      "en": "Foreign national courts"
    },
    "base": {
      "uk": "Іноземні національні суди",
      "en": "Foreign national courts"
    }
  },
  {
    "id": "about.whoH",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Частина ширшої місії",
      "en": "Part of a wider mission"
    },
    "base": {
      "uk": "Частина ширшої місії",
      "en": "Part of a wider mission"
    }
  },
  {
    "id": "about.who2",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Через дослідження, освіту та відкритий доступ до правового знання ми прагнемо сприяти осмисленню того, як право може служити інструментом захисту людини, встановлення відповідальності та відновлення справедливості.",
      "en": "Through research, education and open access to legal knowledge we seek to help make sense of how the law can serve as an instrument for protecting the person, establishing accountability and restoring justice."
    },
    "base": {
      "uk": "Через дослідження, освіту та відкритий доступ до правового знання ми прагнемо сприяти осмисленню того, як право може служити інструментом захисту людини, встановлення відповідальності та відновлення справедливості.",
      "en": "Through research, education and open access to legal knowledge we seek to help make sense of how the law can serve as an instrument for protecting the person, establishing accountability and restoring justice."
    }
  },
  {
    "id": "about.centreLink",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Центр Луї Зона",
      "en": "The Louis Sohn Centre"
    },
    "base": {
      "uk": "Центр Луї Зона",
      "en": "The Louis Sohn Centre"
    }
  },
  {
    "id": "about.teamH",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Хто над цим працює",
      "en": "Who works on this"
    },
    "base": {
      "uk": "Хто над цим працює",
      "en": "Who works on this"
    }
  },
  {
    "id": "about.teamLink",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Сторінка команди",
      "en": "The team page"
    },
    "base": {
      "uk": "Сторінка команди",
      "en": "The team page"
    }
  },
  {
    "id": "about.centre",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Дослідницький центр Луї Зона Факультету права УКУ – експертна платформа з дослідження, осмислення та подолання правових викликів, спричинених війною та повоєнним відновленням України. Центр зʼявився з переконання, що право не може мовчати, коли йдеться про порушення справедливості та гідності людини.",
      "en": "The Louis Sohn Research Centre at the UCU Faculty of Law is an expert platform for researching, making sense of and answering the legal challenges caused by the war and by Ukraine’s post-war recovery. The Centre grew out of a conviction that the law cannot stay silent where justice and human dignity are violated."
    },
    "base": {
      "uk": "Дослідницький центр Луї Зона Факультету права УКУ – експертна платформа з дослідження, осмислення та подолання правових викликів, спричинених війною та повоєнним відновленням України. Центр зʼявився з переконання, що право не може мовчати, коли йдеться про порушення справедливості та гідності людини.",
      "en": "The Louis Sohn Research Centre at the UCU Faculty of Law is an expert platform for researching, making sense of and answering the legal challenges caused by the war and by Ukraine’s post-war recovery. The Centre grew out of a conviction that the law cannot stay silent where justice and human dignity are violated."
    }
  },
  {
    "id": "about.centre2",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Центр поєднує науковий аналіз із практичними правовими рішеннями: тут проводять дослідження, ведуть публічний діалог і сприяють професійному розвитку правників, готових шукати відповіді на найскладніші виклики свого часу. Ця бібліотека – одна з таких відповідей.",
      "en": "The Centre joins scholarly analysis to practical legal work: it conducts research, holds public debate, and supports the professional development of lawyers willing to take on the hardest questions of their time. This library is one of those answers."
    },
    "base": {
      "uk": "Центр поєднує науковий аналіз із практичними правовими рішеннями: тут проводять дослідження, ведуть публічний діалог і сприяють професійному розвитку правників, готових шукати відповіді на найскладніші виклики свого часу. Ця бібліотека – одна з таких відповідей.",
      "en": "The Centre joins scholarly analysis to practical legal work: it conducts research, holds public debate, and supports the professional development of lawyers willing to take on the hardest questions of their time. This library is one of those answers."
    }
  },
  {
    "id": "about.missionH",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Місія Центру",
      "en": "The Centre’s mission"
    },
    "base": {
      "uk": "Місія Центру",
      "en": "The Centre’s mission"
    }
  },
  {
    "id": "about.voice",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Університет має своєю місією суспільне служіння. Факультет права має це служіння не лише у вихованні правників нової генерації, але й у тому, аби долучатися до процесів трансформації суспільства. Дослідницький центр є тим експертним майданчиком, тим осередком, де будуть формуватися та осмислюватися правові відповіді на виклики, які повʼязані з війною.",
      "en": "The university’s mission is service to society. For the Faculty of Law that service lies not only in bringing up a new generation of lawyers, but in taking part in the transformation of society itself. The Research Centre is the expert forum, the place where legal answers to the challenges of the war will be formed and thought through."
    },
    "base": {
      "uk": "Університет має своєю місією суспільне служіння. Факультет права має це служіння не лише у вихованні правників нової генерації, але й у тому, аби долучатися до процесів трансформації суспільства. Дослідницький центр є тим експертним майданчиком, тим осередком, де будуть формуватися та осмислюватися правові відповіді на виклики, які повʼязані з війною.",
      "en": "The university’s mission is service to society. For the Faculty of Law that service lies not only in bringing up a new generation of lawyers, but in taking part in the transformation of society itself. The Research Centre is the expert forum, the place where legal answers to the challenges of the war will be formed and thought through."
    }
  },
  {
    "id": "about.voiceBy",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Ольга Денькович",
      "en": "Olha Denkovych"
    },
    "base": {
      "uk": "Ольга Денькович",
      "en": "Olha Denkovych"
    }
  },
  {
    "id": "about.voiceRole",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "керівниця Центру Луї Зона",
      "en": "Head of the Louis Sohn Centre"
    },
    "base": {
      "uk": "керівниця Центру Луї Зона",
      "en": "Head of the Louis Sohn Centre"
    }
  },
  {
    "id": "about.contactH",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Написати нам",
      "en": "Write to us"
    },
    "base": {
      "uk": "Написати нам",
      "en": "Write to us"
    }
  },
  {
    "id": "about.contact",
    "group": "Про проєкт: сторінка",
    "text": {
      "uk": "Помітили помилку в огляді або знаєте про провадження, якого тут немає – напишіть.",
      "en": "If you have spotted an error in a summary, or know of a proceeding that is missing, write to us."
    },
    "base": {
      "uk": "Помітили помилку в огляді або знаєте про провадження, якого тут немає – напишіть.",
      "en": "If you have spotted an error in a summary, or know of a proceeding that is missing, write to us."
    }
  },
  {
    "id": "blog.title",
    "group": "Блог",
    "text": {
      "uk": "Блог",
      "en": "Blog"
    },
    "base": {
      "uk": "Блог",
      "en": "Blog"
    }
  },
  {
    "id": "blog.metaDesc",
    "group": "Блог",
    "text": {
      "uk": "Дописи редакції «НаСвітло»: нові рішення, пояснення до оглядів і події Дослідницького центру Луї Зона.",
      "en": "Notes from the nasvitlo editors: new decisions, context for the summaries, and events at the Louis Sohn Research Centre."
    },
    "base": {
      "uk": "Дописи редакції «НаСвітло»: нові рішення, пояснення до оглядів і події Дослідницького центру Луї Зона.",
      "en": "Notes from the nasvitlo editors: new decisions, context for the summaries, and events at the Louis Sohn Research Centre."
    }
  },
  {
    "id": "blog.toBlog",
    "group": "Блог",
    "text": {
      "uk": "Усі дописи",
      "en": "All posts"
    },
    "base": {
      "uk": "Усі дописи",
      "en": "All posts"
    }
  },
  {
    "id": "blog.related",
    "group": "Блог",
    "text": {
      "uk": "Огляди, про які йдеться",
      "en": "Summaries discussed"
    },
    "base": {
      "uk": "Огляди, про які йдеться",
      "en": "Summaries discussed"
    }
  },
  {
    "id": "blog.tags",
    "group": "Блог",
    "text": {
      "uk": "Теми",
      "en": "Topics"
    },
    "base": {
      "uk": "Теми",
      "en": "Topics"
    }
  },
  {
    "id": "case.glanceH",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Картка справи",
      "en": "Case at a glance"
    },
    "base": {
      "uk": "Картка справи",
      "en": "Case at a glance"
    }
  },
  {
    "id": "case.timeline",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Хронологія",
      "en": "Timeline"
    },
    "base": {
      "uk": "Хронологія",
      "en": "Timeline"
    }
  },
  {
    "id": "case.tracks",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Географія справи",
      "en": "Case geography"
    },
    "base": {
      "uk": "Географія справи",
      "en": "Case geography"
    }
  },
  {
    "id": "case.violation",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Встановлено порушення",
      "en": "Violation established"
    },
    "base": {
      "uk": "Встановлено порушення",
      "en": "Violation established"
    }
  },
  {
    "id": "case.noViolation",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Встановлено відсутність порушення",
      "en": "No violation established"
    },
    "base": {
      "uk": "Встановлено відсутність порушення",
      "en": "No violation established"
    }
  },
  {
    "id": "case.sources",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Джерела та коментарі",
      "en": "Sources and commentary"
    },
    "base": {
      "uk": "Джерела та коментарі",
      "en": "Sources and commentary"
    }
  },
  {
    "id": "case.back",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "До бібліотеки",
      "en": "Back to the library"
    },
    "base": {
      "uk": "До бібліотеки",
      "en": "Back to the library"
    }
  },
  {
    "id": "case.readJudgment",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Читати рішення",
      "en": "Read the judgment"
    },
    "base": {
      "uk": "Читати рішення",
      "en": "Read the judgment"
    }
  },
  {
    "id": "case.caseFile",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Справа на сайті Суду",
      "en": "Case file at the Court"
    },
    "base": {
      "uk": "Справа на сайті Суду",
      "en": "Case file at the Court"
    }
  },
  {
    "id": "case.keyRulings",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Ключові тлумачення",
      "en": "Key rulings on the law"
    },
    "base": {
      "uk": "Ключові тлумачення",
      "en": "Key rulings on the law"
    }
  },
  {
    "id": "case.provMeasures",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Тимчасові заходи",
      "en": "Provisional measures"
    },
    "base": {
      "uk": "Тимчасові заходи",
      "en": "Provisional measures"
    }
  },
  {
    "id": "case.orderBreached",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Наказ порушено",
      "en": "Order breached"
    },
    "base": {
      "uk": "Наказ порушено",
      "en": "Order breached"
    }
  },
  {
    "id": "case.orderComplied",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Дотримано",
      "en": "Complied"
    },
    "base": {
      "uk": "Дотримано",
      "en": "Complied"
    }
  },
  {
    "id": "case.onThisPage",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "На цій сторінці",
      "en": "On this page"
    },
    "base": {
      "uk": "На цій сторінці",
      "en": "On this page"
    }
  },
  {
    "id": "case.claimed",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Сторона твердила",
      "en": "The party argued"
    },
    "base": {
      "uk": "Сторона твердила",
      "en": "The party argued"
    }
  },
  {
    "id": "case.courtPosition",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Позиція Суду",
      "en": "The Court's position"
    },
    "base": {
      "uk": "Позиція Суду",
      "en": "The Court's position"
    }
  },
  {
    "id": "case.ordered",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Наказано",
      "en": "Ordered"
    },
    "base": {
      "uk": "Наказано",
      "en": "Ordered"
    }
  },
  {
    "id": "case.mapAlt",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Мапа Європи: місце розгляду справи та території, яких вона стосується – перелічені під мапою",
      "en": "Map of Europe: the seat of the proceedings and the territories concerned – listed below the map"
    },
    "base": {
      "uk": "Мапа Європи: місце розгляду справи та території, яких вона стосується – перелічені під мапою",
      "en": "Map of Europe: the seat of the proceedings and the territories concerned – listed below the map"
    }
  },
  {
    "id": "case.granted",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Задоволено",
      "en": "Upheld"
    },
    "base": {
      "uk": "Задоволено",
      "en": "Upheld"
    }
  },
  {
    "id": "case.rejected",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Відхилено",
      "en": "Rejected"
    },
    "base": {
      "uk": "Відхилено",
      "en": "Rejected"
    }
  },
  {
    "id": "case.notDecided",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Не розглядалося",
      "en": "Not decided"
    },
    "base": {
      "uk": "Не розглядалося",
      "en": "Not decided"
    }
  },
  {
    "id": "case.convicted",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Засуджено",
      "en": "Convicted"
    },
    "base": {
      "uk": "Засуджено",
      "en": "Convicted"
    }
  },
  {
    "id": "case.acquitted",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Виправдано",
      "en": "Acquitted"
    },
    "base": {
      "uk": "Виправдано",
      "en": "Acquitted"
    }
  },
  {
    "id": "case.allEvents",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Усе",
      "en": "All"
    },
    "base": {
      "uk": "Усе",
      "en": "All"
    }
  },
  {
    "id": "case.trackFilter",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Фільтр за напрямом",
      "en": "Filter by track"
    },
    "base": {
      "uk": "Фільтр за напрямом",
      "en": "Filter by track"
    }
  },
  {
    "id": "case.openDetail",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Показати деталі",
      "en": "Show detail"
    },
    "base": {
      "uk": "Показати деталі",
      "en": "Show detail"
    }
  },
  {
    "id": "case.mapPick",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Натисніть позначку або рядок – засвітиться те саме місце.",
      "en": "Press a mark or a line – the same place lights up."
    },
    "base": {
      "uk": "Натисніть позначку або рядок – засвітиться те саме місце.",
      "en": "Press a mark or a line – the same place lights up."
    }
  },
  {
    "id": "case.railLabel",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Перейти до події за датою",
      "en": "Jump to an event by date"
    },
    "base": {
      "uk": "Перейти до події за датою",
      "en": "Jump to an event by date"
    }
  },
  {
    "id": "case.shareOf",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "від суми",
      "en": "of the total"
    },
    "base": {
      "uk": "від суми",
      "en": "of the total"
    }
  },
  {
    "id": "case.ofWhole",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "з",
      "en": "of"
    },
    "base": {
      "uk": "з",
      "en": "of"
    }
  },
  {
    "id": "case.attributionH",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Чия поведінка – це поведінка держави",
      "en": "Whose conduct counts as the State's"
    },
    "base": {
      "uk": "Чия поведінка – це поведінка держави",
      "en": "Whose conduct counts as the State's"
    }
  },
  {
    "id": "case.objectionLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Заперечення",
      "en": "Objection"
    },
    "base": {
      "uk": "Заперечення",
      "en": "Objection"
    }
  },
  {
    "id": "case.rulingLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Рішення суду",
      "en": "Ruling"
    },
    "base": {
      "uk": "Рішення суду",
      "en": "Ruling"
    }
  },
  {
    "id": "case.objRejected",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Відхилено",
      "en": "Rejected"
    },
    "base": {
      "uk": "Відхилено",
      "en": "Rejected"
    }
  },
  {
    "id": "case.objUpheld",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Прийнято",
      "en": "Upheld"
    },
    "base": {
      "uk": "Прийнято",
      "en": "Upheld"
    }
  },
  {
    "id": "case.standing",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Рішення чинне",
      "en": "Award stands"
    },
    "base": {
      "uk": "Рішення чинне",
      "en": "Award stands"
    }
  },
  {
    "id": "case.notStanding",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Рішення скасовано",
      "en": "Award annulled"
    },
    "base": {
      "uk": "Рішення скасовано",
      "en": "Award annulled"
    }
  },
  {
    "id": "case.seatLabel",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Місце розгляду",
      "en": "Seat"
    },
    "base": {
      "uk": "Місце розгляду",
      "en": "Seat"
    }
  },
  {
    "id": "case.chargesLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Звинувачення",
      "en": "Charges"
    },
    "base": {
      "uk": "Звинувачення",
      "en": "Charges"
    }
  },
  {
    "id": "case.modesLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Форма відповідальності",
      "en": "Mode of responsibility"
    },
    "base": {
      "uk": "Форма відповідальності",
      "en": "Mode of responsibility"
    }
  },
  {
    "id": "case.announcementLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Повідомлення Суду",
      "en": "The Court's announcement"
    },
    "base": {
      "uk": "Повідомлення Суду",
      "en": "The Court's announcement"
    }
  },
  {
    "id": "case.warCrimeLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Воєнний злочин",
      "en": "War crime"
    },
    "base": {
      "uk": "Воєнний злочин",
      "en": "War crime"
    }
  },
  {
    "id": "case.cahLbl",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Злочин проти людяності",
      "en": "Crime against humanity"
    },
    "base": {
      "uk": "Злочин проти людяності",
      "en": "Crime against humanity"
    }
  },
  {
    "id": "case.asOf",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "станом на",
      "en": "as of"
    },
    "base": {
      "uk": "станом на",
      "en": "as of"
    }
  },
  {
    "id": "case.navAria",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Розділи сторінки",
      "en": "Page sections"
    },
    "base": {
      "uk": "Розділи сторінки",
      "en": "Page sections"
    }
  },
  {
    "id": "case.toTop",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Нагору",
      "en": "Top"
    },
    "base": {
      "uk": "Нагору",
      "en": "Top"
    }
  },
  {
    "id": "case.ofLargest",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "від найбільшої суми тут",
      "en": "of the largest sum here"
    },
    "base": {
      "uk": "від найбільшої суми тут",
      "en": "of the largest sum here"
    }
  },
  {
    "id": "case.dotCap",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "На полі показано перші {n} позначок.",
      "en": "The field draws the first {n} marks."
    },
    "base": {
      "uk": "На полі показано перші {n} позначок.",
      "en": "The field draws the first {n} marks."
    }
  },
  {
    "id": "case.navFulltext",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Повний огляд",
      "en": "Full summary"
    },
    "base": {
      "uk": "Повний огляд",
      "en": "Full summary"
    }
  },
  {
    "id": "case.officialH",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Офіційні документи Суду",
      "en": "Official court documents"
    },
    "base": {
      "uk": "Офіційні документи Суду",
      "en": "Official court documents"
    }
  },
  {
    "id": "case.commentaryH",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "Дослідження та коментарі",
      "en": "Research and commentary"
    },
    "base": {
      "uk": "Дослідження та коментарі",
      "en": "Research and commentary"
    }
  },
  {
    "id": "case.updated",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "оновлено",
      "en": "updated"
    },
    "base": {
      "uk": "оновлено",
      "en": "updated"
    }
  },
  {
    "id": "case.typeLabel.blog post",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "допис у блозі",
      "en": "blog post"
    },
    "base": {
      "uk": "допис у блозі",
      "en": "blog post"
    }
  },
  {
    "id": "case.typeLabel.journal article",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "стаття в журналі",
      "en": "journal article"
    },
    "base": {
      "uk": "стаття в журналі",
      "en": "journal article"
    }
  },
  {
    "id": "case.typeLabel.news/insight",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "новини / аналітика",
      "en": "news / insight"
    },
    "base": {
      "uk": "новини / аналітика",
      "en": "news / insight"
    }
  },
  {
    "id": "case.typeLabel.preprint/repository",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "препринт / репозиторій",
      "en": "preprint / repository"
    },
    "base": {
      "uk": "препринт / репозиторій",
      "en": "preprint / repository"
    }
  },
  {
    "id": "case.typeLabel.official/ICC",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "офіційний документ МКС",
      "en": "ICC official document"
    },
    "base": {
      "uk": "офіційний документ МКС",
      "en": "ICC official document"
    }
  },
  {
    "id": "case.typeLabel.official/award",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "текст рішення",
      "en": "award text"
    },
    "base": {
      "uk": "текст рішення",
      "en": "award text"
    }
  },
  {
    "id": "case.typeLabel.official/court",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "рішення суду",
      "en": "court judgment"
    },
    "base": {
      "uk": "рішення суду",
      "en": "court judgment"
    }
  },
  {
    "id": "case.typeLabel.official/treaty",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "текст договору",
      "en": "treaty text"
    },
    "base": {
      "uk": "текст договору",
      "en": "treaty text"
    }
  },
  {
    "id": "case.typeLabel.official/filing",
    "group": "Сторінка рішення: підписи",
    "text": {
      "uk": "процесуальний документ",
      "en": "court filing"
    },
    "base": {
      "uk": "процесуальний документ",
      "en": "court filing"
    }
  },
  {
    "id": "privacy.revised",
    "group": "Політика приватності: підписи",
    "text": {
      "uk": "Редакція від",
      "en": "Revised"
    },
    "base": {
      "uk": "Редакція від",
      "en": "Revised"
    }
  },
  {
    "id": "privacy.also",
    "group": "Політика приватності: підписи",
    "text": {
      "uk": "Як користуватися матеріалами Сайту й на яких умовах – про це",
      "en": "How the Site’s materials may be used, and on what terms –"
    },
    "base": {
      "uk": "Як користуватися матеріалами Сайту й на яких умовах – про це",
      "en": "How the Site’s materials may be used, and on what terms –"
    }
  },
  {
    "id": "privacy.terms",
    "group": "Політика приватності: підписи",
    "text": {
      "uk": "Умови користування",
      "en": "Terms of use"
    },
    "base": {
      "uk": "Умови користування",
      "en": "Terms of use"
    }
  },
  {
    "id": "library.title",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    },
    "base": {
      "uk": "Бібліотека рішень",
      "en": "Library of decisions"
    }
  },
  {
    "id": "library.lede",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Провадження проти Росії у міжнародних судах, трибуналах та арбітражах. Кожен рядок має рік відкриття провадження, а де рішення вже ухвалене – його точну дату. Дві окремі колонки кажуть, на якому етапі провадження – стан розгляду – і що саме суд ухвалив – тип рішення.",
      "en": "Proceedings against Russia across international courts, tribunals and arbitrations. Each row carries the year the proceeding was opened and, where a decision has been handed down, its exact date. Two separate columns carry the stage of the proceedings and the type of decision the court issued."
    },
    "base": {
      "uk": "Провадження проти Росії у міжнародних судах, трибуналах та арбітражах. Кожен рядок має рік відкриття провадження, а де рішення вже ухвалене – його точну дату. Дві окремі колонки кажуть, на якому етапі провадження – стан розгляду – і що саме суд ухвалив – тип рішення.",
      "en": "Proceedings against Russia across international courts, tribunals and arbitrations. Each row carries the year the proceeding was opened and, where a decision has been handed down, its exact date. Two separate columns carry the stage of the proceedings and the type of decision the court issued."
    }
  },
  {
    "id": "library.metaDesc",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "{n} проваджень проти Росії в міжнародних судах, трибуналах і арбітражах – з фільтрами за судом, станом розгляду і типом рішення.",
      "en": "{n} proceedings against Russia before international courts, tribunals and arbitrations, filterable by court, by stage of proceedings and by type of decision."
    },
    "base": {
      "uk": "{n} проваджень проти Росії в міжнародних судах, трибуналах і арбітражах – з фільтрами за судом, станом розгляду і типом рішення.",
      "en": "{n} proceedings against Russia before international courts, tribunals and arbitrations, filterable by court, by stage of proceedings and by type of decision."
    }
  },
  {
    "id": "library.search",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Сторона, суд, номер справи, рік, тема…",
      "en": "Party, court, docket number, year, subject…"
    },
    "base": {
      "uk": "Сторона, суд, номер справи, рік, тема…",
      "en": "Party, court, docket number, year, subject…"
    }
  },
  {
    "id": "library.searchLabel",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Пошук у бібліотеці",
      "en": "Search the library"
    },
    "base": {
      "uk": "Пошук у бібліотеці",
      "en": "Search the library"
    }
  },
  {
    "id": "library.courts",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Суди",
      "en": "Courts"
    },
    "base": {
      "uk": "Суди",
      "en": "Courts"
    }
  },
  {
    "id": "library.courtsAll",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Усі суди",
      "en": "All courts"
    },
    "base": {
      "uk": "Усі суди",
      "en": "All courts"
    }
  },
  {
    "id": "library.stages",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Стан розгляду",
      "en": "Stage"
    },
    "base": {
      "uk": "Стан розгляду",
      "en": "Stage"
    }
  },
  {
    "id": "library.stagesAll",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Будь-який стан",
      "en": "Any stage"
    },
    "base": {
      "uk": "Будь-який стан",
      "en": "Any stage"
    }
  },
  {
    "id": "library.outcomes",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Тип рішення",
      "en": "Decision type"
    },
    "base": {
      "uk": "Тип рішення",
      "en": "Decision type"
    }
  },
  {
    "id": "library.outcomesAll",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Будь-який тип рішення",
      "en": "Any decision type"
    },
    "base": {
      "uk": "Будь-який тип рішення",
      "en": "Any decision type"
    }
  },
  {
    "id": "library.materials",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Стан опрацювання",
      "en": "Editorial state"
    },
    "base": {
      "uk": "Стан опрацювання",
      "en": "Editorial state"
    }
  },
  {
    "id": "library.materialsAll",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Будь-який стан",
      "en": "Any state"
    },
    "base": {
      "uk": "Будь-який стан",
      "en": "Any state"
    }
  },
  {
    "id": "library.filters",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Фільтри",
      "en": "Filters"
    },
    "base": {
      "uk": "Фільтри",
      "en": "Filters"
    }
  },
  {
    "id": "library.matLit",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Є огляд",
      "en": "Summary ready"
    },
    "base": {
      "uk": "Є огляд",
      "en": "Summary ready"
    }
  },
  {
    "id": "library.matWip",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "В процесі опрацювання",
      "en": "Being worked on"
    },
    "base": {
      "uk": "В процесі опрацювання",
      "en": "Being worked on"
    }
  },
  {
    "id": "library.doc",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Документ суду",
      "en": "The court's document"
    },
    "base": {
      "uk": "Документ суду",
      "en": "The court's document"
    }
  },
  {
    "id": "library.sort",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Порядок",
      "en": "Sort"
    },
    "base": {
      "uk": "Порядок",
      "en": "Sort"
    }
  },
  {
    "id": "library.sortOpt.decidedDesc",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "За датою рішення",
      "en": "By decision date"
    },
    "base": {
      "uk": "За датою рішення",
      "en": "By decision date"
    }
  },
  {
    "id": "library.sortOpt.readable",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Спершу опрацьовані",
      "en": "Ready to read first"
    },
    "base": {
      "uk": "Спершу опрацьовані",
      "en": "Ready to read first"
    }
  },
  {
    "id": "library.sortOpt.court",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "За судом",
      "en": "By court"
    },
    "base": {
      "uk": "За судом",
      "en": "By court"
    }
  },
  {
    "id": "library.colCourt",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Суд",
      "en": "Court"
    },
    "base": {
      "uk": "Суд",
      "en": "Court"
    }
  },
  {
    "id": "library.colCase",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Справа",
      "en": "Case"
    },
    "base": {
      "uk": "Справа",
      "en": "Case"
    }
  },
  {
    "id": "library.colStage",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Стан розгляду",
      "en": "Stage"
    },
    "base": {
      "uk": "Стан розгляду",
      "en": "Stage"
    }
  },
  {
    "id": "library.colOutcome",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Тип рішення",
      "en": "Decision type"
    },
    "base": {
      "uk": "Тип рішення",
      "en": "Decision type"
    }
  },
  {
    "id": "library.colDate",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Рік",
      "en": "Year"
    },
    "base": {
      "uk": "Рік",
      "en": "Year"
    }
  },
  {
    "id": "library.sortAsc",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "за зростанням",
      "en": "sorted ascending"
    },
    "base": {
      "uk": "за зростанням",
      "en": "sorted ascending"
    }
  },
  {
    "id": "library.sortDesc",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "за спаданням",
      "en": "sorted descending"
    },
    "base": {
      "uk": "за спаданням",
      "en": "sorted descending"
    }
  },
  {
    "id": "library.sortNone",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "не сортовано",
      "en": "not sorted"
    },
    "base": {
      "uk": "не сортовано",
      "en": "not sorted"
    }
  },
  {
    "id": "library.ofTotal",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "з {total}",
      "en": "of {total}"
    },
    "base": {
      "uk": "з {total}",
      "en": "of {total}"
    }
  },
  {
    "id": "library.actsNote",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "про які відомо публічно",
      "en": "those on the public record"
    },
    "base": {
      "uk": "про які відомо публічно",
      "en": "those on the public record"
    }
  },
  {
    "id": "library.combine",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Кілька значень в одному фільтрі – будь-яке з них; різні фільтри діють разом.",
      "en": "Several values in one filter mean any of them; different filters apply together."
    },
    "base": {
      "uk": "Кілька значень в одному фільтрі – будь-яке з них; різні фільтри діють разом.",
      "en": "Several values in one filter mean any of them; different filters apply together."
    }
  },
  {
    "id": "library.reset",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Скинути",
      "en": "Reset"
    },
    "base": {
      "uk": "Скинути",
      "en": "Reset"
    }
  },
  {
    "id": "library.activeFilters",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Активні фільтри",
      "en": "Active filters"
    },
    "base": {
      "uk": "Активні фільтри",
      "en": "Active filters"
    }
  },
  {
    "id": "library.clearFilter",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Прибрати фільтр",
      "en": "Remove filter"
    },
    "base": {
      "uk": "Прибрати фільтр",
      "en": "Remove filter"
    }
  },
  {
    "id": "library.clearSearch",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Очистити пошук",
      "en": "Clear search"
    },
    "base": {
      "uk": "Очистити пошук",
      "en": "Clear search"
    }
  },
  {
    "id": "library.emptyHead",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Нічого не знайдено",
      "en": "Nothing found"
    },
    "base": {
      "uk": "Нічого не знайдено",
      "en": "Nothing found"
    }
  },
  {
    "id": "library.emptyBody",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Спробуйте змінити фільтри або пошуковий запит.",
      "en": "Try adjusting the filters or the search query."
    },
    "base": {
      "uk": "Спробуйте змінити фільтри або пошуковий запит.",
      "en": "Try adjusting the filters or the search query."
    }
  },
  {
    "id": "library.searchLoading",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Пошук поки що лише в рядках – покажчик конспектів ще завантажується.",
      "en": "Searching the rows only for now – the write-up index is still loading."
    },
    "base": {
      "uk": "Пошук поки що лише в рядках – покажчик конспектів ще завантажується.",
      "en": "Searching the rows only for now – the write-up index is still loading."
    }
  },
  {
    "id": "library.searchNoIndex",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Покажчик конспектів не завантажився – пошук лише в рядках.",
      "en": "The write-up index did not load – this is searching the rows only."
    },
    "base": {
      "uk": "Покажчик конспектів не завантажився – пошук лише в рядках.",
      "en": "The write-up index did not load – this is searching the rows only."
    }
  },
  {
    "id": "library.matched",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "збіг:",
      "en": "matched:"
    },
    "base": {
      "uk": "збіг:",
      "en": "matched:"
    }
  },
  {
    "id": "library.matchedIn",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "в огляді:",
      "en": "in the write-up:"
    },
    "base": {
      "uk": "в огляді:",
      "en": "in the write-up:"
    }
  },
  {
    "id": "library.section.overview",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Картка справи",
      "en": "Case at a glance"
    },
    "base": {
      "uk": "Картка справи",
      "en": "Case at a glance"
    }
  },
  {
    "id": "library.section.chronology",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Хронологія",
      "en": "Timeline"
    },
    "base": {
      "uk": "Хронологія",
      "en": "Timeline"
    }
  },
  {
    "id": "library.section.machinery",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Розбір рішення",
      "en": "Anatomy"
    },
    "base": {
      "uk": "Розбір рішення",
      "en": "Anatomy"
    }
  },
  {
    "id": "library.section.rulings",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Тлумачення",
      "en": "Key rulings"
    },
    "base": {
      "uk": "Тлумачення",
      "en": "Key rulings"
    }
  },
  {
    "id": "library.section.measures",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Тимчасові заходи",
      "en": "Provisional measures"
    },
    "base": {
      "uk": "Тимчасові заходи",
      "en": "Provisional measures"
    }
  },
  {
    "id": "library.section.fulltext",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Повний огляд",
      "en": "Full summary"
    },
    "base": {
      "uk": "Повний огляд",
      "en": "Full summary"
    }
  },
  {
    "id": "library.group.court",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "суд",
      "en": "court"
    },
    "base": {
      "uk": "суд",
      "en": "court"
    }
  },
  {
    "id": "library.group.status",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "статус",
      "en": "status"
    },
    "base": {
      "uk": "статус",
      "en": "status"
    }
  },
  {
    "id": "library.group.type",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "галузь",
      "en": "field"
    },
    "base": {
      "uk": "галузь",
      "en": "field"
    }
  },
  {
    "id": "library.group.date",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "дата",
      "en": "date"
    },
    "base": {
      "uk": "дата",
      "en": "date"
    }
  },
  {
    "id": "library.group.visible",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "назва",
      "en": "name"
    },
    "base": {
      "uk": "назва",
      "en": "name"
    }
  },
  {
    "id": "library.decidedOn",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "рішення",
      "en": "decided"
    },
    "base": {
      "uk": "рішення",
      "en": "decided"
    }
  },
  {
    "id": "library.noDate",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "–",
      "en": "–"
    },
    "base": {
      "uk": "–",
      "en": "–"
    }
  },
  {
    "id": "library.mProceedings",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "проваджень",
      "en": "proceedings"
    },
    "base": {
      "uk": "проваджень",
      "en": "proceedings"
    }
  },
  {
    "id": "library.mInstitutions",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "інстанцій",
      "en": "institutions"
    },
    "base": {
      "uk": "інстанцій",
      "en": "institutions"
    }
  },
  {
    "id": "library.mAnalysed",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "опрацьовано",
      "en": "analysed"
    },
    "base": {
      "uk": "опрацьовано",
      "en": "analysed"
    }
  },
  {
    "id": "library.state",
    "group": "Бібліотека рішень: сторінка",
    "text": {
      "uk": "Частину проваджень ми вже опрацювали й підсвітили, над іншими ще працюємо.",
      "en": "We have already worked through some of these proceedings and lit them up; we are still working on the others."
    },
    "base": {
      "uk": "Частину проваджень ми вже опрацювали й підсвітили, над іншими ще працюємо.",
      "en": "We have already worked through some of these proceedings and lit them up; we are still working on the others."
    }
  },
  {
    "id": "team.title",
    "group": "Команда: сторінка",
    "text": {
      "uk": "Команда",
      "en": "Team"
    },
    "base": {
      "uk": "Команда",
      "en": "Team"
    }
  },
  {
    "id": "team.metaDesc",
    "group": "Команда: сторінка",
    "text": {
      "uk": "Дослідники, редактори й технічна команда бібліотеки рішень «насвітло».",
      "en": "The researchers, editors and technical team behind the nasvitlo library of decisions."
    },
    "base": {
      "uk": "Дослідники, редактори й технічна команда бібліотеки рішень «насвітло».",
      "en": "The researchers, editors and technical team behind the nasvitlo library of decisions."
    }
  },
  {
    "id": "team.contact",
    "group": "Команда: сторінка",
    "text": {
      "uk": "Написати нам",
      "en": "Write to us"
    },
    "base": {
      "uk": "Написати нам",
      "en": "Write to us"
    }
  },
  {
    "id": "team.contactH",
    "group": "Команда: сторінка",
    "text": {
      "uk": "Написати нам",
      "en": "Write to us"
    },
    "base": {
      "uk": "Написати нам",
      "en": "Write to us"
    }
  },
  {
    "id": "team.contactText",
    "group": "Команда: сторінка",
    "text": {
      "uk": "Помітили помилку в огляді або знаєте про провадження, якого тут немає – напишіть.",
      "en": "If you have spotted an error in a summary, or know of a proceeding that is missing, write to us."
    },
    "base": {
      "uk": "Помітили помилку в огляді або знаєте про провадження, якого тут немає – напишіть.",
      "en": "If you have spotted an error in a summary, or know of a proceeding that is missing, write to us."
    }
  },
  {
    "id": "terms.revised",
    "group": "Умови користування: підписи",
    "text": {
      "uk": "Редакція від",
      "en": "Revised"
    },
    "base": {
      "uk": "Редакція від",
      "en": "Revised"
    }
  },
  {
    "id": "terms.also",
    "group": "Умови користування: підписи",
    "text": {
      "uk": "Які персональні дані ми отримуємо й що з ними робимо – про це",
      "en": "What personal data reaches us and what we do with it –"
    },
    "base": {
      "uk": "Які персональні дані ми отримуємо й що з ними робимо – про це",
      "en": "What personal data reaches us and what we do with it –"
    }
  },
  {
    "id": "terms.privacy",
    "group": "Умови користування: підписи",
    "text": {
      "uk": "Політика конфіденційності",
      "en": "Privacy policy"
    },
    "base": {
      "uk": "Політика конфіденційності",
      "en": "Privacy policy"
    }
  },
  {
    "id": "pend.amount",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "Сума у спорі",
      "en": "Amount in dispute"
    },
    "base": {
      "uk": "Сума у спорі",
      "en": "Amount in dispute"
    }
  },
  {
    "id": "pend.pages",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "Обсяг рішення",
      "en": "Length of the decision"
    },
    "base": {
      "uk": "Обсяг рішення",
      "en": "Length of the decision"
    }
  },
  {
    "id": "pend.pagesN",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "с.",
      "en": "pp."
    },
    "base": {
      "uk": "с.",
      "en": "pp."
    }
  },
  {
    "id": "pend.siblings",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "Інші провадження в цьому суді",
      "en": "Other proceedings before this forum"
    },
    "base": {
      "uk": "Інші провадження в цьому суді",
      "en": "Other proceedings before this forum"
    }
  },
  {
    "id": "pend.kindred",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "Розібрані рішення тієї ж категорії",
      "en": "Analysed decisions of the same kind"
    },
    "base": {
      "uk": "Розібрані рішення тієї ж категорії",
      "en": "Analysed decisions of the same kind"
    }
  },
  {
    "id": "pend.caption",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "Повна назва",
      "en": "Full caption"
    },
    "base": {
      "uk": "Повна назва",
      "en": "Full caption"
    }
  },
  {
    "id": "pend.hasSummary",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "є розбір",
      "en": "analysed"
    },
    "base": {
      "uk": "є розбір",
      "en": "analysed"
    }
  },
  {
    "id": "pend.allOfForum",
    "group": "Сторінка «Ще досліджуємо»: підписи",
    "text": {
      "uk": "Усі провадження цього суду",
      "en": "All proceedings before this forum"
    },
    "base": {
      "uk": "Усі провадження цього суду",
      "en": "All proceedings before this forum"
    }
  }
];
